# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
  };
in
{
  mcp-hub = nodeEnv.buildNodePackage {
    name = "mcp-hub";
    packageName = "mcp-hub";
    version = "4.2.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/mcp-hub/-/mcp-hub-4.2.1.tgz";
      sha512 = "GLtfsYwgtLMS0gyapxn+PTtS/3BX4dmQFqYg6oXjlk0udaYVWMLvMG50G9Nh/2ydzbeihxFMmwXBycr5TdA2AA==";
    };
    dependencies = [
      sources."json5-2.2.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A manager server for MCP servers that handles process management and tool routing";
      homepage = "https://github.com/ravitemer/mcp-hub#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
